package com.izaron.cf.helper;

public enum Achievement {
    FIRST_BLOOD,

    CPP_STUDENT, CPP_MASTER, CPP_WIZARD,
    JAVA_STUDENT, JAVA_MASTER, JAVA_WIZARD,
    PYTHON_STUDENT, PYTHON_MASTER, PYTHON_WIZARD,
    PASCAL_STUDENT, PASCAL_MASTER, PASCAL_WIZARD,
    EXOTIC_WEAPON,

    EXPERIENCED_WARRIOR,
    THUNDERSTORM_WARRIOR,

    HERO_OF_THE_DAY,

    PAINKILLER
}
